### ISSUE TITLE
Don't do ReadAllItems on start-up

### ISSUE THREAD

**Issue by jonas-koeritz** [mailsvb/WorkPointInterface#1]
OpenStage phones are already very slow and unresponsive on startup. If you send a "ReadAllItems" request immediatly on first DLS contact this will slow down the phone even more.

**Comment by mailsvb** [comment]
It has never been discovered that the phone is slow (in general) when doing the ReadAllItems reply, it just takes a while until the phone responds to the ReadAllItems reply.
This is not an issue until the timeout of the server running the script has a low value.
